some tigger-add functionality

diff --git a/tigger-init b/tigger-init
--- a/tigger-init
+++ b/tigger-init
@@ -4,30 +4,29 @@
 . tigger-utilities
 
 
+#make sure no arguments
+[ $# -ne 0 ] && die "usage: $PRGRM"
 
-[ $# -ne 0 ] && die "usage: $TGGR"
 
-
-
-[ -d '.tigger' ] && die "$TGGR: error: .tigger already exists"
+[ -d '.tigger' ] && die "$PRGRM: error: .tigger already exists"
 
 
 #initialise the repo if it doesnt exist.
 if [ ! -d "$REPO" ]
 then
-	mkdir -- "$REPO"                      || die "$TGGR: error: unable to create .tigger"
-	mkdir -- "$REPO/commit"               || die "$TGGR: error: unable to create commit"
-	mkdir -- "$REPO/index"                || die "$TGGR: error: unable to create index"
-	mkdir -- "$REPO/heads"                || die "$TGGR: error: unable to create heads"
-	echo -n "NULL" > "$REPO/heads/master" || die "$TGGR: error: unable to create master branch"
-	echo -n "master" > "$REPO/HEAD"       || die "$TGGR: error: unable to create HEAD"
-	touch  "$REPO/.log"                   || die "$TGGR: error: unable to create .log"
+	mkdir -- "$REPO"                      || die "$PRGRM: error: unable to create .tigger"
+	mkdir -- "$REPO/commit"               || die "$PRGRM: error: unable to create commit"
+	mkdir -- "$REPO/index"                || die "$PRGRM: error: unable to create index"
+	mkdir -- "$REPO/heads"                || die "$PRGRM: error: unable to create heads"
+	echo -n "NULL" > "$REPO/heads/master" || die "$PRGRM: error: unable to create master branch"
+	echo -n "master" > "$REPO/HEAD"       || die "$PRGRM: error: unable to create HEAD"
+	touch  "$REPO/.log"                   || die "$PRGRM: error: unable to create .log"
 
 	
 	echo "Initialized empty tigger repository in .tigger"
 	exit 0
 
 else
-	die "$TGGR: error: .tigger already exists" 
+	die "$PRGRM: error: .tigger already exists" 
 fi
 
